language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/ev1l0rd/ev1l0rd.github.io.git
  - REPO_TARGET_BRANCH: master
  - secure: cG9zbj2Hbt/uy/uaIUFf920aE+WCMJgagra3YKdwRxNjlHvXY0/bNqz23gmozcQIrP916BQrRwn1AFbZMUf3B3VTv2FdEp2x/zzo4qMeTB4qk0Xy2dzlAaZ5GA/lgrvjFd63M8Yrsec8shvxjlBxjF5+ABXTMx5xOz0bT0MCetk2mD3nCNPYq3PuVJSI29CILPyrjVisRgeV4XGhnU2b+7xtCOjcUmgWy9OfkQymUx60kL8UJj+NDw2cJOduhQRP47M0i2p/kXnLHezO3PpUZfWeLwLweBK6sG6KQ0pBN7JmbfCrGnxyu9q5ECnsxLkxGPQEOxWJa45WDA/uEkQ78lThoKihmQ4K34nFYS+fls5oc1k0aEdXNDZR7feGkehMQfiYXOsplT33UoVjmYEipH+bkgAZ9whFPTN1GjpOIb+SuMBO5RlteEPrWYPondnVD6XCITIbfzxqmc74gmKRgTBl8WDq6C9MPVOOYTr6x/ydrFTOXKW3/FauUDf7mpUR7sEUUmeNHxfee988Zl/AEDwlvvPlgSySn2PRALlMKpbZhByX1WZUCjn0GNRb68gO1IpevR+Qu/BleOHTt/p1yFvEtnhsqihYRllzrSp3gslkcDewrmMcl5RzRbC2uMBb3Z7Gb5aUB11fN6HAViVz8py93fK1QPhL4xvWDDy2QUU=
  - secure: FpvXUEbKCxlQa435aWdiWtMSvNQTcOQOWMOKfgb8NteRSXEC99GIMrxUc4obl+1/KRqBA8n9unqgpIEEe8LjgW7b9pTBuWWbvWcRPNhV0r/n9EB+vfQDce5lwBvWOtaDIfYIbxwuaa8EpDSLJLP/z+cBSZFdQF9+t1c2ZAJXPNbH2h/+XrdIYd3/BkS/J/WsAro+Z/yDe0OqnRSk4cUDO5GTx0yBmfcyl5JLKKwALz1asn3PkeLVvC1dG6LGQCiORygj3MsOieehv9ukWid+wHpD5dvlwuC0n1Eh4v6kQEp9BJhZfi5IJtywolEYtByyeDlg3zMGMu+T/w+mBdWB7cvIRPY+tGAgfZ2vHxsmTKWkFu/wwl/X+xxPzx/XspllyPXUxNX8WK6k9gCcD3IWoY7DraXcZpUTJrgNiNHUmQAC9F014USKxdETrl87lZv+cZhTCOWkp1EjreiLwGq001CTJjl7MYTH15w5NLufWOUtxA02JqkZvVo96uxsTrwxHcCOzZh8p1eLT6fr3BUTevQztbs3cJB5ypbEB+M0TQO2I8gSHF7s3ovUm4UOHy40bqFQYt8ECHwtBGSeiIys4morEDv+jS5SnwGNkQuhBqL77ytQQ98UuVJGk4A6aSOY465VUBFWf8e31n+H2fvve7xhC9Q1D88MB5AMD4h8LsQ=
