# Site settings
email: private@ev1l0rd.esy.es
baseurl: 
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Ev1l0rd
description: Blag
url: "ev1l0rd.github.io"
twitter_username: ev1l0rd 
default_img: 

# Profile settings
name: ev1l0rd
profile_img: http://cdn.mspaintadventures.com/storyfiles/hs2/02490_2.gif
profile: Blag. I talk about stuff.
social:
  github: ev1l0rd

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
