# Site settings
email: private@ev1l0rd.esy.es
baseurl: 
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-68539616-1

# SEO settings
title: Ev1l0rd
description: Blag
url: "https://ev1l0rd.github.io"
twitter_username: ev1l0rd 
default_img: https://ev1l0rd.github.io/images/avatar.png

# Profile settings
name: Valentijn
profile_img: https://ev1l0rd.github.io/images/avatar.png
profile: '16 years old, Gamer, Programmer, Blogger, Shitposter, Homestuck. Potential hypocrite.'
social:
  github: https://github.com/ev1l0rd
  twitter: https://twitter.com/ev1l0rd
  steam: https://steamcommunity.com/id/draconiandignitary
  tumblr: https://ev1l0rd.tumblr.com
  reddit: https://reddit.com/u/darknesswizard

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
