title: noirscapes Blog
description: >
  Strongly worded opinions. My views expressed here are my own and not of any of my employers. 
copyright: Valentijn V.
sass:
  sass_dir: assets/sass
url: https://noirscape.github.io
disqus_shortname: 
facebook_username:
twitter_username: "ev1l0rd"
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "noirscape"
discord_guild: "https://discord.gg/Q6jmQcV"
feed_icon: rss
email:
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
excerpt_separator: "\n\n"
