title: ev1l0rd
description: "Mental stability up for discussion."
# url: "http://oneohthree.github.io"
url: "http://ev1l0rd.github.io"
twitter_username: ev1l0rd
github_username:  ev1l0rd
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown

# Disqus settings
disqus: ev1l0rd

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68539616-1

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
